name: Pull requests check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x.x
          cache: 'npm'

      - run: npm ci
      if: always()
      - run: npm run build:prod
      if: always()
      - run: npm run lint:ts
      if: always()
      - run: npm run lint:scss
      if: always()
      - run: npm run test:unit
      if: always()
      - run: npm run storybook:build
      if: always()
      - run: npm run test:ui:ci
